scoop install bat;
scoop install tealdeer;
scoop install sccache;
scoop install ripgrep;
scoop install helix;
scoop install clangd;
scoop install nu;
scoop install hyperfine;
scoop install zoxide;
scoop install fd;
scoop install fzf;
scoop install starship;
cargo install --locked bacon;
cargo install du-dust;
cargo install speedtest-rs;
