[[language]]
name = "python"
language-servers = ["pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true

[[language]]
name = "cpp"
language-servers = ["clangd"]
auto-format = true
formatter = { command = "clang-format", args = ["--style=Google"] }

[language-server.clangd]
command = "clangd"
args = ["--background-index", "--clang-tidy"]

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["--style=Google"] }
